# Generated by Django 2.2.6 on 2019-11-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModifyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('change_type', models.CharField(max_length=20)),
                ('change_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('assets_type', models.CharField(max_length=20)),
                ('currency_type', models.CharField(default='RMB', max_length=10)),
                ('exchange_rate', models.IntegerField(default=1)),
                ('code', models.CharField(default='000', max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalNetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
