# Generated by Django 2.2.6 on 2019-11-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_category', models.CharField(choices=[('Cash', '现金'), ('Stock', '股票'), ('Fund', '基金'), ('Near Cash', '类现金'), ('Insurance', '保险'), ('Credit', '信用卡'), ('Bond', '债券'), ('Fixed', '定期理财'), ('Others', '其他理财'), ('Receivable', '应收'), ('payable', '应付')], default='Cash', max_length=100)),
                ('holding_account', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('Asset', '资产'), ('Debt', '负债')], default='Assets', max_length=20)),
                ('code', models.CharField(default='000000', max_length=10)),
                ('market', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(choices=[('RMB', '人民币'), ('HKD', '港元'), ('USD', '美元')], default='RMB', max_length=10, unique=True)),
                ('code', models.CharField(default='CNY', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoldingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TotalNetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('change_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='net.Assets')),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='currency',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='net.Currency'),
        ),
    ]
