# Generated by Django 2.2.6 on 2019-11-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netmodel',
            old_name='name',
            new_name='assets_name',
        ),
        migrations.RemoveField(
            model_name='netmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='netmodel',
            name='assets_category',
            field=models.CharField(choices=[('Cash', '现金'), ('Stocks', '股票'), ('Funds', '基金'), ('Near Cash', '类现金'), ('Insurance', '保险'), ('Credit', '信用卡'), ('Bonds', '债券'), ('Fixed', '定期理财'), ('Others', '其他理财')], default='Cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='modifymodel',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='modifymodel',
            name='change_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='modifymodel',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='assets_type',
            field=models.CharField(choices=[('Assets', '资产'), ('Debts', '负债')], default='Assets', max_length=20),
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='code',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='currency_type',
            field=models.CharField(choices=[('RMB', '人民币'), ('HKD', '港元'), ('USD', '美元')], default='RMB', max_length=10),
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='exchange_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='totalnetmodel',
            name='total',
            field=models.FloatField(),
        ),
    ]
