# Generated by Django 2.2.6 on 2019-11-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0003_auto_20191105_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='netmodel',
            name='holding_account',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='netmodel',
            name='assets_category',
            field=models.CharField(choices=[('Cash', '现金'), ('Stocks', '股票'), ('Funds', '基金'), ('Near Cash', '类现金'), ('Insurance', '保险'), ('Credit', '信用卡'), ('Bonds', '债券'), ('Fixed', '定期理财'), ('Others', '其他理财'), ('Receivables', '应收'), ('payable', '应付')], default='Cash', max_length=100),
        ),
    ]
