# Generated by Django 2.2.6 on 2019-11-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0003_auto_20191109_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='holding_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net.HoldingAccount'),
        ),
    ]
