# Generated by Django 2.2.6 on 2019-11-07 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0004_auto_20191106_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(choices=[('RMB', '人民币'), ('HKD', '港元'), ('USD', '美元')], default='RMB', max_length=10)),
                ('exchange_rate', models.FloatField(default=1.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='netmodel',
            name='exchange_rate',
        )
    ]
