# Generated by Django 2.2.6 on 2019-11-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0005_auto_20191107_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmodel',
            name='currency_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
