# Generated by Django 2.2.6 on 2019-11-07 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0006_auto_20191107_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmodel',
            name='currency_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='net.ExchangeRate'),
        ),
    ]
