# Generated by Django 2.2.6 on 2019-11-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0007_auto_20191107_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangeRate',
            new_name='CurrencyType',
        ),
        migrations.RenameField(
            model_name='currencytype',
            old_name='currency_type',
            new_name='currency_type_name',
        ),
    ]
