# Generated by Django 2.2.6 on 2019-11-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0008_auto_20191107_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencytype',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
