# Generated by Django 2.2.6 on 2019-11-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0010_auto_20191107_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencytype',
            name='code',
            field=models.CharField(default='CHY', max_length=10),
        ),
        migrations.AddField(
            model_name='netmodel',
            name='market',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
