# Generated by Django 2.2.6 on 2019-11-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0011_auto_20191107_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmodel',
            name='market',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
