# Generated by Django 2.2.6 on 2019-11-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0012_auto_20191107_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytype',
            name='code',
            field=models.CharField(default='CNY', max_length=10),
        ),
    ]
